-- 파일명이 schema.sql 이어야 한다! ( 규칙임 )
drop table if exists item CASCADE;

create table item
(
    id bigint generated by default as identity ,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);